name: Run CI on Main and Feature Branches

on:
  push:
    branches:
      - main         # push to main
      - feature/**   # push to any feature branch
  pull_request:
    branches:
      - main         # PR target is main

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/